plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'net.darkhax.curseforgegradle'
    id 'com.modrinth.minotaur'
}

repositories {
    mavenLocal()
    maven {
        name = 'Curse Maven'
        url = 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven { url "https://maven.shedaniel.me/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modImplementation("curse.maven:cloth-config-348521:${cloth_config_version}")
    modImplementation("curse.maven:modmenu-308702:${mod_menu_version}")
    modImplementation("me.shedaniel.cloth:basic-math:0.6.1")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

tasks.register('publishCurseForge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    apiToken = findProperty('cf_api_token')
    // The main file to upload
    def mainFile = upload(cf_project, file("${project.buildDir}/libs/${archivesBaseName}-${version}.jar"))
    mainFile.displayName = "FixMySpawneR-fabric-${minecraft_version}-${version}"
    mainFile.releaseType = "${release}"
    mainFile.changelog = "${changelog}"
    mainFile.changelogType = 'markdown'
    mainFile.addJavaVersion('Java 17')
    mainFile.addGameVersion("${minecraft_version}")
    mainFile.addModLoader('fabric')
    mainFile.addModLoader('quilt')
    mainFile.addRequirement('fabric-api')
}

modrinth {

    token.set(project.findProperty('modrinth_api_token'))
    projectId.set(modrinth_project)
    changelog = "${changelog}"
    versionName.set("${mod_name}-Fabric-${minecraft_version}-$version")
    versionType.set("${releasetype}")
    uploadFile.set(tasks.remapJar)
    dependencies {
        required.project("fabric-api")
    }
    gameVersions = ["${minecraft_version}"]
}